### ISSUE TITLE
How to use the map/scene editor?

### ISSUE THREAD

**Issue by ilija04** [Rubberduckycooly/RetroED#2]
If you are active on here, please help me. I know how to use every editor except the map/scene editor. What kind of data directory i need to specify? I tried every folder, and it keeps saying it's not a valid data directory. I think you should provide a tutorial on how to use it, I definetely recommend it.

**Comment by Xeroxtheplanet** [comment]
I had some trouble and have no idea if you have solved it yet, but it must be the "Data" folder in your game files. Nothing more, nothing less.

**Comment by ilija04** [comment]
Yeah you need to select the Data folder in order for it to work, I figured it out a long time ago.
